name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [ published, prereleased ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      # Conditionally build in release mode if this is a release event,
      # otherwise perform a standard build.
      - name: Build
        run: |
          if [ "${{ github.event_name }}" == "release" ]; then
            cargo build --release --verbose
          else
            cargo build --verbose
          fi
      
      - name: Run tests
        run: cargo test --verbose
      
      # Only upload the artifact on a release event (new release or pre-release)
      - name: Upload artifact
        if: ${{ github.event_name == 'release' }}
        uses: actions/upload-artifact@v3
        with:
          name: rust-artifact
          path: target/release/your_binary_name.exe
